In [9]:
import pandas as pd

jobs = pd.DataFrame([
    {"job": "J1", "proc_time": 3, "due": 10},
    {"job": "J2", "proc_time": 6, "due": 12},
    {"job": "J3", "proc_time": 2, "due": 8},
    {"job": "J4", "proc_time": 4, "due": 15},
])

current_time = 5

In [10]:
jobs["fifo_rank"] = range(1, len(jobs) + 1)

In [11]:
jobs["slack"] = jobs["due"] - (current_time + jobs["proc_time"])
jobs["priority_score"] = jobs["slack"]

In [12]:
recommendation = jobs.sort_values("priority_score")

recommendation[["job", "proc_time", "due", "slack"]]

  job  proc_time  due  slack
1  J2          6   12      1
2  J3          2    8      1
0  J1          3   10      2
3  J4          4   15      6

In [13]:
def explain(row):
    if row.slack < 0:
        return "すでに遅れリスクあり"
    elif row.slack < 2:
        return "納期が近い"
    else:
        return "比較的余裕あり"

recommendation["reason"] = recommendation.apply(explain, axis=1)

In [14]:
recommendation[["job", "slack", "reason"]]

  job  slack   reason
1  J2      1    納期が近い
2  J3      1    納期が近い
0  J1      2  比較的余裕あり
3  J4      6  比較的余裕あり

In [15]:
def recommend_next_job(jobs, current_time):
    jobs = jobs.copy()
    jobs["slack"] = jobs["due"] - (current_time + jobs["proc_time"])
    jobs = jobs.sort_values("slack")
    return jobs[["job", "proc_time", "due", "slack"]]

In [16]:
recommend_next_job(jobs, current_time)

  job  proc_time  due  slack
1  J2          6   12      1
2  J3          2    8      1
0  J1          3   10      2
3  J4          4   15      6